---

# PHP
php_ini_settings:
  - section: PHP
    option: upload_max_filesize
    value: 11M
  - section: Date
    option: date.timezone
    value: "{{ timezone }}"

php_fpm_settings:
  - { option: user,   value: "{{ app_user }}" }
  - { option: group,  value: "{{ app_user }}" }
