---

- name: PHP | Alter php.ini
  sudo: yes
  ini_file: >
    dest=/etc/php5/fpm/php.ini
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    backup=yes
  with_items:
    - { section: PHP,  option: upload_max_filesize, value: "{{ php_ini_upload_max_filesize }}" }
    - { section: Date, option: date.timezone,       value: "{{ timezone }}" }
  notify:
  - restart php-fpm

- name: PHP | Setup FPM pool
  sudo: yes
  ini_file: >
    dest=/etc/php5/fpm/pool.d/www.conf
    section=www
    option={{ item.option }}
    value={{ item.value }}
    backup=yes
  with_items:
    - { option: user,   value: "{{ app_user }}" }
    - { option: group,  value: "{{ app_user }}" }

    - { option: listen,                 value: "{{ php_fpm_listen }}" }
    - { option: listen.allowed_clients, value: "127.0.0.1" }
    - { option: listen.mode,            value: "0600" }

    - { option: pm.max_children,      value: "{{ php_fpm_max_children }}" }
    - { option: pm.start_servers,     value: "{{ php_fpm_start_servers }}" }
    - { option: pm.min_spare_servers, value: "{{ php_fpm_min_spare_servers }}" }
    - { option: pm.max_spare_servers, value: "{{ php_fpm_max_spare_servers }}" }
  notify:
  - restart php-fpm
