---

- name: PHP | Alter php.ini
  sudo: yes
  ini_file: >
    dest=/etc/php5/fpm/php.ini
    section={{ item.section }}
    option={{ item.option }}
    value={{ item.value }}
    backup=yes
  with_items:
    - { section: PHP,  option: upload_max_filesize, value: "{{ php_ini_upload_max_filesize }}" }
    - { section: Date, option: date.timezone,       value: "{{ timezone }}" }
