---

- name: Install PHP
  apt: name={{ item }} state=latest
  sudo: yes
  with_items:
    - php5
    - php5-fpm
    - php5-cli

- name: Install PHP libraries
  apt: name={{ item }} state=latest
  sudo: yes
  with_items:
    - php5-mysql
    - php5-curl
    - php5-gd
