---

- name: Install PHP
  apt: name={{ item }} state=latest
  sudo: yes
  with_items:
    - php5
    - php5-fpm
    - php5-cli

- name: Install PHP extensions
  apt: name={{ item }} state=latest
  sudo: yes
  with_items: php_extensions_defaults + php_extensions
  notify: restart php-fpm
